#!/usr/bin/env python3
"""
Add Generated DOIs to BibTeX
============================
Adds DOIs generated by doi_strategy.py to bcm_master.bib

Usage:
    python scripts/add_generated_dois.py              # Dry run
    python scripts/add_generated_dois.py --apply      # Apply changes
    python scripts/add_generated_dois.py --verify     # Verify DOIs via CrossRef
"""

import re
import argparse
from pathlib import Path

# Import from doi_strategy
import sys
sys.path.insert(0, str(Path(__file__).parent))
from doi_strategy import (
    load_journal_database,
    parse_bibtex,
    get_doi_strategy,
    generate_doi_from_pattern
)

SCRIPT_DIR = Path(__file__).parent
ROOT_DIR = SCRIPT_DIR.parent
BIB_FILE = ROOT_DIR / "bibliography" / "bcm_master.bib"


def add_doi_to_bibtex(content: str, key: str, doi: str) -> str:
    """Add DOI field to a BibTeX entry."""
    # Find the entry
    pattern = rf'(@\w+\{{{key},.*?)(\n\}})'
    match = re.search(pattern, content, re.DOTALL)

    if not match:
        return content

    entry = match.group(1)

    # Check if DOI already exists
    if re.search(r'^\s*doi\s*=', entry, re.MULTILINE | re.IGNORECASE):
        return content

    # Find a good place to insert (after title or after year)
    # Insert before the closing brace
    new_entry = entry + f',\n  doi = {{{doi}}}'

    return content[:match.start()] + new_entry + match.group(2) + content[match.end():]


def main():
    parser = argparse.ArgumentParser(description='Add generated DOIs to BibTeX')
    parser.add_argument('--apply', action='store_true', help='Apply changes (default: dry run)')
    parser.add_argument('--verify', action='store_true', help='Verify DOIs via CrossRef')
    args = parser.parse_args()

    print("Loading journal database...")
    journal_db = load_journal_database()

    print("Loading bibliography...")
    papers = parse_bibtex()
    papers_without_doi = [p for p in papers if not p.get('doi')]

    print(f"  {len(papers)} total papers")
    print(f"  {len(papers_without_doi)} without DOI")

    # Find papers with PATTERN strategy
    generated = []
    for paper in papers_without_doi:
        result = get_doi_strategy(paper, journal_db)
        if result['strategy'] == 'PATTERN' and result['pattern']:
            doi = generate_doi_from_pattern(paper, result['pattern'])
            if doi:
                generated.append({
                    'key': paper['key'],
                    'doi': doi,
                    'title': paper.get('title', '')[:50],
                    'journal': result['journal_name']
                })

    print(f"\n{len(generated)} DOIs to add:")
    print("-" * 70)

    for g in generated:
        print(f"  {g['key']:<40} {g['doi']}")

    if not args.apply:
        print("\n[DRY RUN] Use --apply to actually add DOIs")
        return

    # Read current BibTeX
    with open(BIB_FILE, 'r', encoding='utf-8') as f:
        content = f.read()

    # Add DOIs
    added = 0
    for g in generated:
        new_content = add_doi_to_bibtex(content, g['key'], g['doi'])
        if new_content != content:
            content = new_content
            added += 1
            print(f"  ✓ Added DOI to {g['key']}")

    # Write back
    with open(BIB_FILE, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"\n{added} DOIs added to {BIB_FILE}")


if __name__ == '__main__':
    main()
