#!/usr/bin/env python3
"""
Auto-Intake Pipeline for BEA Lab Uploads
==========================================

Automatically processes papers uploaded via the BEA Lab frontend
(papers/evaluated/integrated/) and integrates them into the EBF database:

1. Detects new/unprocessed files (TXT, PDF)
2. Extracts metadata (title, authors, year, DOI, journal)
3. Creates BibTeX stub in bcm_master.bib
4. Creates Paper-YAML in data/paper-references/
5. Classifies integration level
6. Adds to paper-integration-queue.yaml

Usage:
    # Status: show what's unprocessed
    python scripts/auto_intake_papers.py --status

    # Process single file (Experiment-First: 1)
    python scripts/auto_intake_papers.py --file "papers/evaluated/integrated/file.txt"

    # Process batch (Experiment-First: 10)
    python scripts/auto_intake_papers.py --batch 10

    # Process all unprocessed files
    python scripts/auto_intake_papers.py --all

    # Dry run (no changes)
    python scripts/auto_intake_papers.py --all --dry-run

    # Filter by type
    python scripts/auto_intake_papers.py --all --type txt
    python scripts/auto_intake_papers.py --all --type pdf

Author: EBF Team
Version: 1.0.0
Date: February 2026
"""

import argparse
import os
import re
import sys
import yaml
from datetime import datetime, date
from pathlib import Path
from typing import Optional

# SSOT import: all key generation logic lives in bibtex_key_generator.py
from bibtex_key_generator import (
    generate_canonical_key as _generate_canonical_key,
    is_canonical as _is_canonical,
    CANONICAL_PATTERN,
)

ROOT = Path(__file__).resolve().parent.parent
INTAKE_DIR = ROOT / "papers" / "evaluated" / "integrated"
BIB_PATH = ROOT / "bibliography" / "bcm_master.bib"
PAPER_REF_DIR = ROOT / "data" / "paper-references"
PAPER_TEXTS_DIR = ROOT / "data" / "paper-texts"
QUEUE_PATH = ROOT / "data" / "paper-integration-queue.yaml"
MANIFEST_PATH = ROOT / "data" / "auto-intake-manifest.yaml"

# File types to skip (not papers)
SKIP_PATTERNS = [
    r"^_.*TEST.*",           # Test files
    r"^Duplikat-Test",       # Duplicate tests
    r"^EBF:",                # EBF system queries
    r"^_PUSH_TEST",          # Push tests
    r"^_BEA_LAB_TEST",       # BEA Lab tests
    r"\.xlsx$",              # Spreadsheets
    r"\.docx$",              # Word docs (not papers)
    r"^Long List",           # Lists
    r"^5_Lernfelder",        # Meta-documents
]

# Known non-paper extensions
NON_PAPER_EXT = {'.xlsx', '.docx', '.pptx', '.zip', '.csv'}

# BEA Lab canonical filename pattern: PAP_Author_Year_Title-Words.ext
# Example: PAP_Kahneman_1979_Prospect-Theory-Analysis-Decision-Under.pdf
BEA_LAB_PATTERN = re.compile(
    r'^(?P<doctype>PAP|BOOK|STU|SSRN)_(?P<author>[A-Za-z]+)_(?P<year>\d{4})_(?P<titleslug>.+)$'
)


def parse_bea_lab_filename(filepath):
    """Parse BEA Lab canonical filename into metadata components.

    Recognizes filenames generated by the BEA Lab frontend:
        PAP_Kahneman_1979_Prospect-Theory-Analysis-Decision-Under.pdf
        BOOK_Thaler_2015_Misbehaving-Science-Behavioral-Economics.pdf
        STU_McKinsey_2024_Global-Survey-Results.pdf

    Returns dict with author, year, title_slug, doc_type — or None if not BEA Lab format.
    """
    stem = filepath.stem
    m = BEA_LAB_PATTERN.match(stem)
    if not m:
        return None

    title_slug = m.group('titleslug').replace('-', ' ')
    return {
        'doc_type': m.group('doctype'),
        'author': m.group('author'),
        'year': m.group('year'),
        'title_slug': title_slug,
    }


def extract_key_from_filename(filepath, existing_keys=None):
    """Try to derive the canonical BibTeX key directly from the filename.

    Three strategies (in priority order):
      1. PAP-{key}.ext → key directly (existing SSOT convention)
      2. BEA Lab format PAP_Author_Year_Title.ext → generate_canonical_key()
      3. Filename IS a canonical key: kahneman1979prospect.ext → use directly

    Returns (bibtex_key, source_hint) or (None, None).
    """
    stem = filepath.stem

    # Strategy 1: PAP-prefix (existing convention in repo)
    if stem.startswith('PAP-'):
        candidate = stem[4:]  # Strip "PAP-"
        if existing_keys is None or candidate in existing_keys:
            return candidate, 'pap_prefix'
        # Fuzzy: case-insensitive
        if existing_keys:
            for ek in existing_keys:
                if ek.lower() == candidate.lower():
                    return ek, 'pap_prefix_fuzzy'

    # Strategy 2: BEA Lab format (PAP_Author_Year_Title-Slug.ext)
    bea = parse_bea_lab_filename(filepath)
    if bea:
        key = _generate_canonical_key(bea['author'], bea['year'], bea['title_slug'])
        return key, 'bea_lab_filename'

    # Strategy 3: Filename is already a canonical key (kahneman1979prospect.ext)
    if _is_canonical(stem):
        return stem, 'canonical_filename'

    return None, None


def validate_filename_key(fn_key, fn_source, metadata):
    """Cross-validate filename-derived key against content-extracted metadata.

    Safety net: if BEA Lab's extract_paper_metadata() produced wrong metadata
    (e.g. "Vol" instead of "Kahneman"), the filename-key will be wrong.
    We catch this by comparing the author in the filename against the author
    extracted from file content.

    Returns:
        (True, reason)  if filename key is trustworthy
        (False, reason) if content disagrees — fall back to content-parsing
    """
    # PAP-prefix and canonical filenames are already validated keys
    if fn_source in ('pap_prefix', 'pap_prefix_fuzzy', 'canonical_filename'):
        return True, 'trusted_format'

    # For BEA Lab filenames, cross-check author
    if fn_source == 'bea_lab_filename':
        content_authors = metadata.get('authors', [])
        if not content_authors:
            # No content author to compare — trust filename
            return True, 'no_content_author'

        # Extract author component from the filename key
        # fn_key format: "kahneman1979prospect"
        m = re.match(r'^([a-z]+)\d{4}', fn_key)
        if not m:
            return False, 'key_parse_failed'

        fn_author = m.group(1)  # e.g. "kahneman"

        # Extract last name from first content author
        first_content_author = content_authors[0]
        if ',' in first_content_author:
            content_lastname = first_content_author.split(',')[0].strip()
        else:
            parts = first_content_author.strip().split()
            content_lastname = parts[-1] if parts else ''

        from bibtex_key_generator import normalize_to_ascii
        content_lastname = normalize_to_ascii(content_lastname).lower()
        content_lastname = re.sub(r'[^a-z]', '', content_lastname)

        if not content_lastname:
            return True, 'no_content_lastname'

        # Compare: exact match or one is prefix of other (handles "Della" vs "DellaVigna")
        if fn_author == content_lastname:
            return True, 'author_match'
        if fn_author.startswith(content_lastname) or content_lastname.startswith(fn_author):
            return True, 'author_prefix_match'

        # Mismatch — content disagrees with filename
        return False, f'author_mismatch:filename={fn_author},content={content_lastname}'

    return True, 'unknown_source'


def load_manifest():
    """Load or create the auto-intake manifest tracking processed files."""
    if MANIFEST_PATH.exists():
        with open(MANIFEST_PATH, 'r', encoding='utf-8') as f:
            data = yaml.safe_load(f) or {}
    else:
        data = {}

    if 'processed' not in data:
        data['processed'] = {}
    if 'skipped' not in data:
        data['skipped'] = {}
    if 'metadata' not in data:
        data['metadata'] = {
            'created': datetime.now().strftime('%Y-%m-%d'),
            'version': '1.0',
            'description': 'Tracks files processed by auto_intake_papers.py'
        }
    return data


def save_manifest(data):
    """Save the manifest."""
    data['metadata']['last_updated'] = datetime.now().strftime('%Y-%m-%dT%H:%M:%S')
    with open(MANIFEST_PATH, 'w', encoding='utf-8') as f:
        yaml.dump(data, f, default_flow_style=False, allow_unicode=True, sort_keys=False)


def should_skip(filename):
    """Check if a file should be skipped (not a paper)."""
    for pattern in SKIP_PATTERNS:
        if re.search(pattern, filename, re.IGNORECASE):
            return True
    ext = Path(filename).suffix.lower()
    if ext in NON_PAPER_EXT:
        return True
    if ext not in {'.txt', '.pdf', '.md'}:
        return True
    return False


def load_existing_bib_data():
    """Load all existing BibTeX keys, DOIs, and titles from bcm_master.bib.
    Returns: (keys_set, doi_to_key_dict, titles_to_key_dict)
    """
    keys = set()
    doi_to_key = {}
    title_to_key = {}

    if BIB_PATH.exists():
        with open(BIB_PATH, 'r', encoding='utf-8') as f:
            content = f.read()

        # Parse entries
        current_key = None
        current_doi = None
        current_title = None

        for line in content.split('\n'):
            m = re.match(r'@\w+\s*\{\s*([^,]+)\s*,', line)
            if m:
                # Save previous entry
                if current_key:
                    if current_doi:
                        doi_to_key[current_doi.lower().strip()] = current_key
                    if current_title:
                        # Normalize title for fuzzy matching
                        norm_title = re.sub(r'[^a-z0-9\s]', '', current_title.lower()).strip()
                        norm_title = re.sub(r'\s+', ' ', norm_title)
                        title_to_key[norm_title] = current_key
                keys.add(m.group(1).strip())
                current_key = m.group(1).strip()
                current_doi = None
                current_title = None
            elif current_key:
                doi_match = re.match(r'\s*doi\s*=\s*\{([^}]+)\}', line, re.IGNORECASE)
                if doi_match:
                    current_doi = doi_match.group(1)
                title_match = re.match(r'\s*title\s*=\s*\{(.+?)(?:\}|$)', line, re.IGNORECASE)
                if title_match:
                    current_title = title_match.group(1)

        # Don't forget last entry
        if current_key:
            if current_doi:
                doi_to_key[current_doi.lower().strip()] = current_key
            if current_title:
                norm_title = re.sub(r'[^a-z0-9\s]', '', current_title.lower()).strip()
                norm_title = re.sub(r'\s+', ' ', norm_title)
                title_to_key[norm_title] = current_key

    return keys, doi_to_key, title_to_key


def find_existing_match(metadata, doi_to_key, title_to_key, existing_keys=None):
    """Check if a paper already exists in BibTeX by DOI, title, or PAP-key match.
    Returns: existing_key or None
    """
    # 0. Filename-based key extraction (PAP-prefix, BEA Lab format, or canonical key)
    source_file = metadata.get('source_file', '')
    if source_file:
        filepath = Path(source_file)
        fn_key, fn_source = extract_key_from_filename(filepath, existing_keys)
        if fn_key and existing_keys:
            # Direct match
            if fn_key in existing_keys:
                metadata['_filename_key'] = fn_key
                metadata['_filename_key_source'] = fn_source
                return fn_key
            # Case-insensitive match
            for ek in existing_keys:
                if ek.lower() == fn_key.lower():
                    metadata['_filename_key'] = ek
                    metadata['_filename_key_source'] = fn_source
                    return ek

    # 1. DOI match (exact)
    doi = metadata.get('doi', '')
    if doi:
        doi_lower = doi.lower().strip()
        if doi_lower in doi_to_key:
            return doi_to_key[doi_lower]

    # 2. Title match (normalized)
    title = metadata.get('title', '')
    if title:
        norm_title = re.sub(r'[^a-z0-9\s]', '', title.lower()).strip()
        norm_title = re.sub(r'\s+', ' ', norm_title)
        if norm_title in title_to_key:
            return title_to_key[norm_title]

        # 3. Fuzzy title match (first 40 chars)
        if len(norm_title) > 30:
            prefix = norm_title[:40]
            for existing_title, key in title_to_key.items():
                if existing_title.startswith(prefix):
                    return key

    return None


def load_existing_paper_yamls():
    """Load all existing PAP-*.yaml paper IDs."""
    ids = set()
    if PAPER_REF_DIR.exists():
        for p in PAPER_REF_DIR.glob('PAP-*.yaml'):
            ids.add(p.stem)  # PAP-xxx
    return ids


def _is_author_line(line):
    """Detect if a line looks like an author list (not a title)."""
    # Pipe-separated names: "Kevin Bauer | Lena Liebich | Oliver Hinz"
    if '|' in line and re.search(r'[A-Z][a-z]+\s+[A-Z]', line):
        parts = [p.strip() for p in line.split('|')]
        name_like = sum(1 for p in parts if re.match(r'^[A-Z][a-z]+', p))
        if name_like >= 2:
            return True
    # Semicolon-separated: "Andersen, Torben M.; Svarer, Michael"
    if ';' in line and re.match(r'^[A-Z][a-z]+,\s+[A-Z]', line):
        return True
    # Comma-separated names: "Dennis Herhausen, Stephan Ludwig, Dhruv Grewal"
    if re.match(r'^[A-Z][a-z]+\s+[A-Z][a-z]+,\s+[A-Z][a-z]+\s+[A-Z]', line):
        return True
    # ALL CAPS short names: "RICHARD  H.  THALER" (tab-separated SSRN style)
    if re.match(r'^[A-Z]{2,}\s+[A-Z]\.?\s+[A-Z]{2,}$', line):
        return True
    # University/affiliation line
    if re.match(r'^(Booth\s|Harvard|MIT|Stanford|University|Department|School|Institute|Center|Centre)', line, re.IGNORECASE):
        return True
    return False


def _is_journal_header(line):
    """Detect if a line is a journal/publisher header (not a title)."""
    journal_headers = [
        r'^PLoS\s', r'^Nature\s', r'^Science\s', r'^The Lancet',
        r'^www\.\w+\.\w+', r'^https?://',
        r'^\d{4}\s', r'^Volume\s+\d', r'^Vol\.\s*\d',
        r'^Open access', r'^freely available',
        r'^August|^September|^October|^November|^December|^January|^February|^March|^April|^May|^June|^July',
        r'^Essay$', r'^\d+$',  # Page numbers, section labels
        r'^Provided in Cooperation', r'^Suggested Citation',
        r'^This Version is available', r'^Standard-Nutzungsbedingungen',
        r'^CESifo Working Paper', r'^IZA Discussion Paper',
        r'^SAFE Working Paper', r'^Discussion Paper',
    ]
    for pattern in journal_headers:
        if re.match(pattern, line, re.IGNORECASE):
            return True
    return False


def _title_from_filename(filepath):
    """Extract a clean title from filename (often the best source for BEA Lab uploads)."""
    name = filepath.stem
    # Remove common prefixes/suffixes
    name = re.sub(r'^\[APE\]_?', '', name)
    name = re.sub(r'SSRN-id\d+$', '', name, flags=re.IGNORECASE)
    name = re.sub(r'v\d+$', '', name, flags=re.IGNORECASE)
    # Clean separators
    name = re.sub(r'[_+]', ' ', name)
    name = re.sub(r'\s+', ' ', name).strip()
    # Skip pure numeric filenames (e.g. "2302.08854", "555973581")
    if re.match(r'^[\d.]+$', name):
        return None
    # Skip very short names
    if len(name) < 5:
        return None
    return name


def extract_metadata_from_txt(filepath):
    """
    Extract metadata from a text file (BEA Lab upload).

    Strategy: Read first ~80 lines and look for structured metadata patterns:
    - DOI patterns (10.xxxx/...)
    - Title (from filename first, validated/improved from text)
    - Authors (lines with comma-separated names, pipe-separated, etc.)
    - Journal names
    - Year (4-digit number)
    """
    try:
        with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
            raw_lines = f.readlines()[:80]
    except Exception as e:
        return {'error': str(e)}

    if not raw_lines:
        return {'error': 'Empty file'}

    # Clean lines: strip whitespace and replace tabs with spaces
    lines = [re.sub(r'\t+', ' ', l).strip() for l in raw_lines]
    # Remove zero-width chars and other artifacts
    lines = [re.sub(r'[\x00-\x08\x0b\x0c\x0e-\x1f]', '', l) for l in lines]

    metadata = {
        'title': None,
        'authors': [],
        'year': None,
        'doi': None,
        'journal': None,
        'source_file': str(filepath.relative_to(ROOT)),
        'extraction_method': 'txt_header_parse',
    }

    full_header = '\n'.join(lines[:50])

    # --- DOI ---
    doi_match = re.search(r'(10\.\d{4,}/[^\s,;]+)', full_header)
    if doi_match:
        doi = doi_match.group(1).rstrip('.')
        metadata['doi'] = doi

    # --- Year ---
    for line in lines[:30]:
        year_match = re.search(r'\b(19[5-9]\d|20[0-2]\d)\b', line)
        if year_match:
            candidate = int(year_match.group(1))
            if 1950 <= candidate <= 2027:
                metadata['year'] = candidate
                break

    # --- APE Paper special handling ---
    filename = filepath.name
    if filename.startswith('[APE]'):
        title_from_name = filename.replace('[APE]_', '').replace('.txt', '')
        title_from_name = title_from_name.replace('_', ' ').strip()
        title_from_name = re.sub(r'\s+', ' ', title_from_name)
        metadata['title'] = title_from_name
        metadata['source_type'] = 'ape_working_paper'
        for line in lines[:10]:
            if re.match(r'^[A-Z][a-z]+ [A-Z]', line) and ',' not in line[:30]:
                metadata['authors'].append(line.split(',')[0].strip())
        return metadata

    # --- Authors (extract before title to use for filtering) ---
    for i, line in enumerate(lines[:20]):
        if _is_author_line(line):
            if '|' in line:
                parts = [p.strip() for p in line.split('|') if p.strip()]
                # Filter out URLs and journal names
                metadata['authors'] = [p for p in parts if re.match(r'^[A-Z][a-z]', p) and 'www' not in p.lower()]
            elif ';' in line:
                parts = re.split(r';\s*', line)
                metadata['authors'] = [p.strip() for p in parts if p.strip()]
            elif ',' in line:
                parts = re.split(r',\s*(?:and\s+)?', line)
                metadata['authors'] = [p.strip() for p in parts if p.strip() and len(p.strip()) > 3]
            if metadata['authors']:
                break

    # --- Title from filename (primary source for BEA Lab uploads) ---
    filename_title = _title_from_filename(filepath)

    # --- Title from text content ---
    text_title = None
    title_candidates = []
    for i, line in enumerate(lines[:20]):
        if not line or len(line) < 10:
            continue
        # Skip known non-title patterns
        if re.match(r'(https?://|DOI|doi:|10\.\d|©|Version of Record|document|Link to|General rights|Copyright|E-mail|Phone|Electronic copy|SSRN|Abstract:|Keywords:|JEL|Manuscript_|ssrn\.com)', line, re.IGNORECASE):
            continue
        if re.match(r'^(VU Research Portal|published in|citation for|Download date|Working Paper|NBER|CEPR|Terms of use|Documents in)', line, re.IGNORECASE):
            continue
        if _is_author_line(line):
            continue
        if _is_journal_header(line):
            continue
        # Clean trailing artifacts (e.g. "ARCHITECTURE0" -> "ARCHITECTURE")
        cleaned = re.sub(r'\d+\s*$', '', line).strip()
        if cleaned and len(cleaned) >= 10:
            title_candidates.append((i, cleaned))

    if title_candidates:
        # Pick the first substantial candidate
        for idx, candidate in title_candidates:
            if len(candidate) > 15:
                text_title = candidate
                break
        if not text_title and title_candidates:
            text_title = title_candidates[0][1]

    # --- Choose best title ---
    # Quality check on text title
    text_title_ok = False
    if text_title:
        # Title must start with uppercase letter (real titles always do)
        starts_upper = bool(re.match(r'^[A-Z"\']', text_title))
        # Not garbage patterns
        not_garbage = not bool(re.search(r'^[A-Z]{2,}\s+[A-Z]{2,}$|^\d|^P$', text_title))
        # Contains at least some real words
        has_words = len(text_title.split()) >= 2
        # No broken PDF artifacts (ligatures etc.)
        no_artifacts = 'ﬁ' not in text_title and 'ﬂ' not in text_title
        text_title_ok = starts_upper and not_garbage and has_words and no_artifacts

    if filename_title and text_title and text_title_ok:
        text_words = len(text_title.split())
        fn_words = len(filename_title.split())
        if text_words >= 3 and text_words > fn_words:
            metadata['title'] = text_title
        else:
            metadata['title'] = filename_title
    elif text_title and text_title_ok:
        metadata['title'] = text_title
    elif filename_title:
        metadata['title'] = filename_title
    elif text_title:
        # Use text title even if not perfect - better than nothing
        metadata['title'] = text_title
    else:
        # Last resort: use raw filename
        name = filepath.stem
        name = re.sub(r'[_]', ' ', name)
        name = re.sub(r'\s+', ' ', name).strip()
        metadata['title'] = name

    # --- Journal ---
    journal_patterns = [
        r'(?:published in|journal of|Journal of)\s+(.+)',
        r'^(Journal of \w[\w\s]+)',
        r'^(American Economic Review|Quarterly Journal of Economics|Econometrica|Review of Economic Studies)',
    ]
    for line in lines[:20]:
        for pattern in journal_patterns:
            m = re.search(pattern, line, re.IGNORECASE)
            if m:
                metadata['journal'] = m.group(1).strip()
                break
        if metadata['journal']:
            break

    return metadata


def extract_metadata_from_pdf(filepath):
    """
    Extract metadata from PDF filename (actual text extraction requires PyMuPDF).
    Falls back to filename-based extraction.
    """
    metadata = {
        'title': None,
        'authors': [],
        'year': None,
        'doi': None,
        'journal': None,
        'source_file': str(filepath.relative_to(ROOT)),
        'extraction_method': 'pdf_filename_parse',
    }

    name = filepath.stem
    # Try to find year in filename
    year_match = re.search(r'(19[5-9]\d|20[0-2]\d)', name)
    if year_match:
        metadata['year'] = int(year_match.group(1))

    # Use improved filename title extraction
    filename_title = _title_from_filename(filepath)
    if filename_title:
        metadata['title'] = filename_title
    else:
        # Pure numeric or very short filename
        metadata['title'] = name

    # Check if companion .txt exists (already extracted)
    txt_path = filepath.with_suffix('.txt')
    if txt_path.exists():
        txt_meta = extract_metadata_from_txt(txt_path)
        # Merge: prefer txt metadata where available
        for key in ['doi', 'journal', 'authors', 'year']:
            if txt_meta.get(key) and (not metadata.get(key) or key == 'authors' and not metadata[key]):
                metadata[key] = txt_meta[key]
        if txt_meta.get('title') and len(txt_meta['title']) > len(metadata.get('title', '')):
            metadata['title'] = txt_meta['title']
        metadata['has_txt_companion'] = True
        metadata['extraction_method'] = 'pdf_with_txt_companion'

    return metadata


def generate_bibtex_key(metadata):
    """Generate a canonical BibTeX key: nachnamejahrkurzwort.

    Delegates to bibtex_key_generator.generate_canonical_key() (SSOT).
    This wrapper adapts the metadata-dict interface used by auto_intake.
    """
    authors = metadata.get('authors', [])
    author_str = authors[0] if authors else ''
    year = metadata.get('year') or '0000'
    title = metadata.get('title', '')

    # ArXiv fallback: if filename is numeric and no author found
    if not author_str:
        source_file = metadata.get('source_file', '')
        source_stem = Path(source_file).stem if source_file else ''
        if re.match(r'^[\d.]+$', source_stem):
            arxiv_id = source_stem.replace('.', '')
            return f"arxiv{year}{arxiv_id}"

    return _generate_canonical_key(author_str, year, title)


def create_bibtex_entry(key, metadata):
    """Create a BibTeX entry string."""
    title = metadata.get('title', 'Unknown Title')
    authors = metadata.get('authors', [])
    year = metadata.get('year', '')
    doi = metadata.get('doi', '')
    journal = metadata.get('journal', '')

    # Format authors for BibTeX
    if authors:
        author_str = ' and '.join(authors)
    else:
        author_str = 'Unknown'

    source_type = metadata.get('source_type', '')
    if source_type == 'ape_working_paper':
        entry_type = 'unpublished'
    elif journal:
        entry_type = 'article'
    else:
        entry_type = 'misc'

    lines = [f"@{entry_type}{{{key},"]
    lines.append(f"  title = {{{title}}},")
    lines.append(f"  author = {{{author_str}}},")
    if year:
        lines.append(f"  year = {{{year}}},")
    if journal:
        lines.append(f"  journal = {{{journal}}},")
    if doi:
        lines.append(f"  doi = {{{doi}}},")

    # EBF fields
    lines.append(f"  use_for = {{LIT-O}},")
    lines.append(f"  evidence_tier = {{3}},")
    lines.append(f"  notes = {{Auto-intake from BEA Lab upload: {metadata.get('source_file', '')}}},")
    lines.append(f"  session_ref = {{auto-intake-{datetime.now().strftime('%Y-%m-%d')}}},")
    lines.append("}")

    return '\n'.join(lines)


def create_paper_yaml(key, metadata):
    """Create a Paper-YAML dict for data/paper-references/PAP-{key}.yaml."""
    today = date.today().isoformat()

    yaml_data = {
        'paper': key,
        'superkey': f'PAP-{key}',
        'title': metadata.get('title', 'Unknown Title'),
        'author': ', '.join(metadata.get('authors', ['Unknown'])),
        'year': str(metadata.get('year', '')),
        'doi': metadata.get('doi', ''),
        'publication_type': 'article' if metadata.get('journal') else 'working_paper',
        'journal': metadata.get('journal', ''),
        'abstract': '',
        'abstract_source': 'pending',
        'full_text': {
            'available': True,
            'path': metadata.get('source_file', ''),
            'format': Path(metadata.get('source_file', '')).suffix.lstrip('.'),
            'content_level': 'L1',
        },
        'ebf_integration': {
            'evidence_tier': 3,
            'use_for': ['LIT-O'],
            'theory_support': '',
            'parameter': '',
            'external_validity': '',
        },
        'prior_score': {
            'prior_score': 0.0,
            'pi_normalized': 0.0,
            'classification': 'MINIMAL',
            'content_level': 'L1',
            'integration_level': 'I1',
            'confidence_multiplier': 0.8,
            'evidence_quality': 0.5,
            'quality_score': {
                'q_C': 0.4,
                'q_I': 0.2,
                'q_total': 0.3,
            },
            'computed_date': today,
        },
        'ssot_migration_date': today,
        'status': 'auto_intake',
        'intake_source': 'bea_lab_upload',
        'intake_date': today,
        'source_file': metadata.get('source_file', ''),
    }

    return yaml_data


def add_to_queue(key, metadata, queue_data):
    """Add paper to integration queue."""
    entry = {
        'paper_id': f'PAP-{key}',
        'level': 1,
        'missing': ['abstract', 'theory_support', 'use_for_refinement'],
        'priority': 'low',
        'attempts': 0,
        'has_full_text': True,
        'track': 'C',
        'content_level': 1,
        'integration_level': 1,
        'note': f"Auto-intake from BEA Lab: {metadata.get('title', '')[:60]}",
        'has_template': False,
        'added_date': date.today().isoformat(),
        'source': 'auto_intake',
    }
    queue_data.append(entry)
    return entry


def process_file(filepath, existing_keys, existing_yamls, doi_to_key, title_to_key, manifest, queue_data, dry_run=False):
    """Process a single file. Returns (status, key, metadata).
    status: 'created', 'linked', 'skipped', 'error'
    """
    filename = filepath.name

    if should_skip(filename):
        manifest['skipped'][filename] = {
            'reason': 'matched_skip_pattern',
            'date': datetime.now().strftime('%Y-%m-%d'),
        }
        return 'skipped', None, None

    # Extract metadata
    ext = filepath.suffix.lower()
    if ext == '.txt':
        metadata = extract_metadata_from_txt(filepath)
    elif ext == '.pdf':
        metadata = extract_metadata_from_pdf(filepath)
    elif ext == '.md':
        metadata = extract_metadata_from_txt(filepath)  # Same parser works
    else:
        return 'skipped', None, None

    if 'error' in metadata:
        print(f"  ERROR: {metadata['error']}")
        manifest['skipped'][filename] = {
            'reason': f"extraction_error: {metadata['error']}",
            'date': datetime.now().strftime('%Y-%m-%d'),
        }
        return 'error', None, None

    # Check if paper already exists by DOI, title, or PAP-key
    existing_key = find_existing_match(metadata, doi_to_key, title_to_key, existing_keys)
    if existing_key:
        print(f"  MATCH: Already in BibTeX as '{existing_key}'")
        manifest['processed'][filename] = {
            'bibtex_key': existing_key,
            'paper_yaml': f"PAP-{existing_key}.yaml",
            'title': metadata.get('title', '')[:80],
            'date': datetime.now().strftime('%Y-%m-%d'),
            'doi': metadata.get('doi', ''),
            'match_type': 'doi_or_title',
            'action': 'linked_existing',
        }
        # Create YAML if it doesn't exist yet
        paper_yaml_id = f"PAP-{existing_key}"
        yaml_path = PAPER_REF_DIR / f"{paper_yaml_id}.yaml"
        if not yaml_path.exists() and not dry_run:
            yaml_data = create_paper_yaml(existing_key, metadata)
            with open(yaml_path, 'w', encoding='utf-8') as f:
                yaml.dump(yaml_data, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
            existing_yamls.add(paper_yaml_id)
            print(f"  → Created missing YAML: {paper_yaml_id}.yaml")
        return 'linked', existing_key, metadata

    # Generate BibTeX key — prefer filename-derived key if validated against content
    fn_key, fn_source = extract_key_from_filename(filepath, existing_keys)
    if fn_key and fn_key not in existing_keys:
        valid, reason = validate_filename_key(fn_key, fn_source, metadata)
        if valid:
            key = fn_key
            print(f"  KEY from filename ({fn_source}, {reason}): {key}")
        else:
            # Safety net: filename disagrees with content → fall back to content-parsing
            key = generate_bibtex_key(metadata)
            print(f"  KEY from content (filename rejected: {reason}): {key}")
    else:
        key = generate_bibtex_key(metadata)

    # Avoid key collisions
    original_key = key
    counter = 2
    while key in existing_keys:
        key = f"{original_key}_{counter}"
        counter += 1

    paper_yaml_id = f"PAP-{key}"
    if paper_yaml_id in existing_yamls:
        manifest['skipped'][filename] = {
            'reason': f"already_exists_as_{paper_yaml_id}",
            'date': datetime.now().strftime('%Y-%m-%d'),
        }
        return 'skipped', key, metadata

    if dry_run:
        return 'created', key, metadata

    # 1. Create BibTeX entry
    bib_entry = create_bibtex_entry(key, metadata)
    with open(BIB_PATH, 'a', encoding='utf-8') as f:
        f.write(f"\n\n{bib_entry}\n")
    existing_keys.add(key)

    # 2. Create Paper-YAML
    yaml_data = create_paper_yaml(key, metadata)
    yaml_path = PAPER_REF_DIR / f"PAP-{key}.yaml"
    with open(yaml_path, 'w', encoding='utf-8') as f:
        yaml.dump(yaml_data, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    existing_yamls.add(paper_yaml_id)

    # 3. Add to queue
    add_to_queue(key, metadata, queue_data)

    # 4. Update manifest
    # Track key source (filename-derived vs content-extracted)
    key_source = 'content_extracted'
    if fn_key and key == fn_key:
        key_source = fn_source  # e.g., 'bea_lab_filename', 'canonical_filename', 'pap_prefix'

    manifest['processed'][filename] = {
        'bibtex_key': key,
        'paper_yaml': f"PAP-{key}.yaml",
        'title': metadata.get('title', '')[:80],
        'date': datetime.now().strftime('%Y-%m-%d'),
        'doi': metadata.get('doi', ''),
        'action': 'created_new',
        'key_source': key_source,
    }

    return 'created', key, metadata


def get_unprocessed_files(manifest, file_type=None):
    """Get list of files not yet processed.
    Deduplicates PDF+TXT pairs: prefers TXT over PDF when both exist.
    Also skips PDF companions of already-processed TXT files (and vice versa).
    """
    processed = set(manifest.get('processed', {}).keys())
    skipped = set(manifest.get('skipped', {}).keys())
    known = processed | skipped

    # Build set of stems that are already processed (any extension)
    known_stems = set()
    for name in known:
        known_stems.add(Path(name).stem)

    # Collect all candidate files
    all_files = {}
    for f in sorted(INTAKE_DIR.iterdir()):
        if f.is_dir():
            continue
        if f.name in known:
            continue
        if should_skip(f.name):
            continue
        stem = f.stem
        ext = f.suffix.lower()
        if ext not in {'.txt', '.pdf', '.md'}:
            continue
        # Skip if any version of this stem is already processed
        if stem in known_stems:
            continue
        if stem not in all_files:
            all_files[stem] = {}
        all_files[stem][ext] = f

    # Deduplicate: prefer TXT over PDF (TXT has better metadata)
    files = []
    for stem, exts in sorted(all_files.items()):
        if file_type:
            target_ext = f'.{file_type}'
            if target_ext in exts:
                files.append(exts[target_ext])
        elif '.txt' in exts:
            files.append(exts['.txt'])
        elif '.md' in exts:
            files.append(exts['.md'])
        elif '.pdf' in exts:
            files.append(exts['.pdf'])

    return files


def show_status(manifest):
    """Show current processing status."""
    processed = manifest.get('processed', {})
    skipped = manifest.get('skipped', {})

    total_files = sum(1 for f in INTAKE_DIR.iterdir() if f.is_file())
    unprocessed = get_unprocessed_files(manifest)

    print("=" * 70)
    print("AUTO-INTAKE PIPELINE STATUS")
    print("=" * 70)
    print(f"\n  Total files in integrated/:  {total_files}")
    print(f"  Processed (in EBF DB):       {len(processed)}")
    print(f"  Skipped (not papers):        {len(skipped)}")
    print(f"  Unprocessed:                 {len(unprocessed)}")
    print()

    if unprocessed:
        # Count by type
        by_ext = {}
        for f in unprocessed:
            ext = f.suffix.lower() or '(no ext)'
            by_ext[ext] = by_ext.get(ext, 0) + 1

        print("  Unprocessed by type:")
        for ext, count in sorted(by_ext.items(), key=lambda x: -x[1]):
            print(f"    {ext:8s}  {count}")

        print(f"\n  Next 5 unprocessed:")
        for f in unprocessed[:5]:
            print(f"    {f.name[:70]}")

    print()


def main():
    parser = argparse.ArgumentParser(description='Auto-intake papers from BEA Lab uploads')
    parser.add_argument('--status', action='store_true', help='Show processing status')
    parser.add_argument('--file', type=str, help='Process a single file')
    parser.add_argument('--batch', type=int, help='Process N files')
    parser.add_argument('--all', action='store_true', help='Process all unprocessed files')
    parser.add_argument('--dry-run', action='store_true', help='Show what would be done')
    parser.add_argument('--type', type=str, choices=['txt', 'pdf', 'md'], help='Filter by file type')
    parser.add_argument('--reset-skipped', action='store_true', help='Reset skipped files for reprocessing')

    args = parser.parse_args()

    manifest = load_manifest()

    if args.reset_skipped:
        manifest['skipped'] = {}
        save_manifest(manifest)
        print("Skipped files reset.")
        return

    if args.status:
        show_status(manifest)
        return

    # Load existing data
    existing_keys, doi_to_key, title_to_key = load_existing_bib_data()
    existing_yamls = load_existing_paper_yamls()

    # Load queue
    queue_data = []

    # Determine files to process
    if args.file:
        files = [Path(args.file)]
        if not files[0].is_absolute():
            files = [ROOT / files[0]]
    elif args.batch:
        files = get_unprocessed_files(manifest, args.type)[:args.batch]
    elif args.all:
        files = get_unprocessed_files(manifest, args.type)
    else:
        parser.print_help()
        return

    if not files:
        print("No files to process.")
        return

    mode = "DRY RUN" if args.dry_run else "PROCESSING"
    print(f"\n{'=' * 70}")
    print(f"AUTO-INTAKE PIPELINE — {mode}")
    print(f"{'=' * 70}")
    print(f"Files to process: {len(files)}\n")

    success_count = 0
    linked_count = 0
    skip_count = 0
    error_count = 0

    for i, filepath in enumerate(files, 1):
        print(f"[{i}/{len(files)}] {filepath.name[:60]}")

        if not filepath.exists():
            print(f"  FILE NOT FOUND\n")
            error_count += 1
            continue

        status, key, metadata = process_file(
            filepath, existing_keys, existing_yamls, doi_to_key, title_to_key,
            manifest, queue_data, dry_run=args.dry_run
        )

        if status == 'created':
            success_count += 1
            title = metadata.get('title', '')[:50] if metadata else ''
            doi = metadata.get('doi', '') or 'no DOI'
            print(f"  → NEW: {key}")
            print(f"    Title: {title}")
            print(f"    DOI: {doi}")
            if args.dry_run:
                print(f"    [DRY RUN — would create BibTeX + YAML + Queue entry]")
        elif status == 'linked':
            linked_count += 1
            print(f"  → LINKED to existing: {key}")
        elif status == 'error':
            error_count += 1
        else:
            skip_count += 1
            if key:
                print(f"  → SKIPPED (already exists as PAP-{key})")
            else:
                print(f"  → SKIPPED")
        print()

    # Save results
    if not args.dry_run and (success_count > 0 or skip_count > 0 or linked_count > 0):
        save_manifest(manifest)

        # Append to queue file if there are new entries
        if queue_data:
            if QUEUE_PATH.exists():
                with open(QUEUE_PATH, 'r', encoding='utf-8') as f:
                    existing_queue = yaml.safe_load(f) or {}
            else:
                existing_queue = {}

            if 'papers' not in existing_queue:
                existing_queue['papers'] = []

            existing_queue['papers'].extend(queue_data)

            with open(QUEUE_PATH, 'w', encoding='utf-8') as f:
                yaml.dump(existing_queue, f, default_flow_style=False, allow_unicode=True, sort_keys=False)

    # Summary
    print(f"{'=' * 70}")
    print(f"SUMMARY")
    print(f"{'=' * 70}")
    print(f"  New papers:       {success_count}")
    print(f"  Linked existing:  {linked_count}")
    print(f"  Skipped:          {skip_count}")
    print(f"  Errors:           {error_count}")
    if not args.dry_run and success_count > 0:
        print(f"\n  Created:")
        print(f"    BibTeX entries:     {success_count} (in bcm_master.bib)")
        print(f"    Paper-YAMLs:        {success_count} (in data/paper-references/)")
        print(f"    Queue entries:      {success_count} (in paper-integration-queue.yaml)")
        print(f"    Manifest updated:   data/auto-intake-manifest.yaml")
    print()


if __name__ == '__main__':
    main()
