#!/bin/bash
# Setup cron jobs for EBF monitoring and backup system
#
# Usage: bash CRON-JOBS-SETUP.sh
#
# This script installs cron jobs for:
# - Hourly metrics collection and alerting
# - Daily backup of entire scope
# - Weekly audit log cleanup
# - Monthly backup archive

set -e

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SCRIPTS_DIR="$REPO_DIR/scripts"

echo "Setting up EBF cron jobs..."
echo "Repository: $REPO_DIR"
echo ""

# Create cron jobs file
CRON_FILE="/tmp/ebf-cron-jobs.txt"

cat > "$CRON_FILE" << 'EOF'
# EBF Operational Framework: Scheduled Jobs
# Generated by CRON-JOBS-SETUP.sh

# Hourly: Metrics collection and alerting (every hour)
0 * * * * cd /path/to/repo && python3 scripts/run_monitoring.py >> logs/monitoring.log 2>&1

# Daily: Backup entire scope (2:00 AM UTC)
0 2 * * * cd /path/to/repo && python3 scripts/run_daily_backup.py >> logs/backup.log 2>&1

# Weekly: Audit log cleanup (Sunday 3:00 AM UTC)
0 3 * * 0 cd /path/to/repo && python3 -c "from scripts.audit_logger import AuditLogger; AuditLogger().cleanup_old_events(30)" >> logs/audit.log 2>&1

# Weekly: Backup verification (Saturday 4:00 AM UTC)
0 4 * * 6 cd /path/to/repo && python3 -c "from scripts.backup_manager import BackupManager; m=BackupManager(); print('Backups:', m.get_backup_stats())" >> logs/backup.log 2>&1

# Monthly: Full system validation (1st of month, 5:00 AM UTC)
0 5 1 * * cd /path/to/repo && python3 scripts/validate_tier4.py >> logs/validation.log 2>&1
EOF

echo "Cron jobs template created: $CRON_FILE"
echo ""

# Instructions
echo "📋 INSTALLATION INSTRUCTIONS"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "1. Update the cron file with your actual repository path:"
echo "   sed -i 's|/path/to/repo|'$REPO_DIR'|g' $CRON_FILE"
echo ""
echo "2. Install the cron jobs:"
echo "   crontab -e"
echo "   # Then paste the contents of $CRON_FILE"
echo ""
echo "3. Verify installation:"
echo "   crontab -l"
echo ""
echo "4. Monitor logs:"
echo "   tail -f logs/monitoring.log"
echo "   tail -f logs/backup.log"
echo ""

# Create log directory
mkdir -p "$REPO_DIR/logs"
echo "✓ Created logs directory"

# Make scripts executable
chmod +x "$SCRIPTS_DIR/run_monitoring.py"
chmod +x "$SCRIPTS_DIR/run_daily_backup.py"
echo "✓ Made scripts executable"

# Create required directories
mkdir -p "$REPO_DIR/data/audit/digests"
mkdir -p "$REPO_DIR/data/backups/tier1"
mkdir -p "$REPO_DIR/data/backups/tier2"
mkdir -p "$REPO_DIR/data/backups/tier3"
mkdir -p "$REPO_DIR/data/metrics"
mkdir -p "$REPO_DIR/data/monitoring"
mkdir -p "$REPO_DIR/data/dependencies"
mkdir -p "$REPO_DIR/data/validation"
echo "✓ Created data directories"

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "✅ Setup complete!"
echo ""
echo "Next steps:"
echo "  1. Edit cron jobs: crontab -e"
echo "  2. Paste contents from: $CRON_FILE"
echo "  3. Update /path/to/repo with: $REPO_DIR"
echo "  4. Save and close"
echo "  5. Verify: crontab -l"
echo ""
